### ISSUE TITLE
Support X-Forwarded-Host header

### ISSUE THREAD

**Issue by yegle** [zyclonite/nassh-relay#11]
I'm using https://github.com/pomerium/pomerium as reverse proxy, and it by default add `X-Forwarded-Host` header.

me -> https://ssh-relay.example.com (Pomerium) -> http://nassh-relay:8022 (in docker)

It looks like nassh-relay will give out `nassh-relay` as the relay server (because Pomerium will act as an HTTP client and send HTTP request to nassh-relay with `Host: nassh-relay`, as well as `X-Forwarded-Host: ssh-relay.example.com`:

```
Found relay server: https://nassh-relay:8022/
```

Is it possible to support `X-Forwarded-Host` header as well? It looks like this is the de-facto standard per https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Host.

**Comment by zyclonite** [comment]
i am not completely sure what you are trying to achieve or what does not work for you...
the server itself does not care about either the host nor the forwarded host...

what could be missing is the `X-Real-IP` header so nassh-relay knows what the real client ip is

**Comment by yegle** [comment]
So in https://github.com/zyclonite/nassh-relay/blob/master/src/main/java/net/zyclonite/nassh/handler/CookieHandler.java#L65, the code assumed the `nassh-relay` server is accessible via the domain name in `Host:` HTTP header.

In the case of Pomerium, the proxied HTTP request to nassh-relay will have a `Host:` header with host name visible to the reverse proxy (in my case, an internal host name `nassh-relay:8022`), while `X-Forwarded-For` header contains the externally accessible host name (in my case, a publicly accessible `ssh-relay.example.com`).

To be more specific, here's the request flow:

me -- (request: `Host: ssh-relay.example.com`) --> Pomerium
Pomerium -- (request: `Host: nassh-relay:8022, X-Forwarded-Host: ssh-relay.example.com`) --> nassh-relay
nassh-relay -- (response: please connect to `http://nassh-relay`) -> me
me: can't access `http://nassh-relay`

**Comment by zyclonite** [comment]
ok, now i get it

yes, this makes sense
if the forwarded host header is set, use it as for the redirect

**Comment by zyclonite** [comment]
should be fixed now, please give feedback if you have still troubles ...
