### ISSUE TITLE
question/request for documentation on accesslist configuration

### ISSUE THREAD

**Issue by qorron** [zyclonite/nassh-relay#2]
suffering from issue #1 I was thinking to allow connections to everywhere if login via g+ works and restrict it to one single target ip if it doesn't.
the source ip doesn't matter in both cases.

how would I do that?

**Comment by zyclonite** [comment]
good question!
this was not possible yet without messy blacklist rules...
i added a whitelist now where you can configure this single host (v1.0.2)

```
"accesslist":[{
  "email":"user@gmail.com",
  "access":[
    {"network":"0.0.0.0/8"},
    {"network":"::/8"}
  ]
},
"whitelist":[
  {"host":"192.168.0.1"}
],
"blacklist":[
  {"network":"0.0.0.0/8"},
  {"network":"::/8"}
]
```

**Comment by qorron** [comment]
nice! thanks!

so instead of the id one can also use the email for authentication with g+?

what about the domain property?
is it possible to specify more than one id or email for one accesslist entry?

**Comment by zyclonite** [comment]
id, email and domain are possible -> domain is only available if you have a google apps account with your private domain (hosted domain)

there is no list of ids possible at the moment, you need to copy the whole entry for another id
