### ISSUE TITLE
using an upstream proxy (nginx) has issues, the relay likes to bypass the proxy

### ISSUE THREAD

**Issue by qorron** [zyclonite/nassh-relay#3]
I tried to use nginx to terminate the ssl connections to nassh-relay.
that didn't work.

what I found out:
the extention first connects to the nginx but after the initial requests it tries to connect to the relay directly.
this doesn't give an error while using http (unless port 8022 is firewalled) because the relay does understand http.

but when https is used, the extention tries to talk https with the relay without using the proxy but the relay doesn't understand that.
somehow it gets the port from the initial requests or it just assumes the default. I haven't found 8022 somewhere in the http tcpdump.

can we talk directly via some IM service? I think that would be more efficient to share the research.

**Comment by zyclonite** [comment]
Can you please provide your nginx config as well as your config.json, so I can test that

**Comment by qorron** [comment]
here we go, ips, names and keys have been replaced by placeholders for privacy reasons.
I have been juggling around with the ports but I haven't found a working solution.
therefore the config as it is now may be further away from a working condition than the original one.

port mapping:
`docker run -d --name nassh-relay -p 8022:443 -v /opt/nassh-relay/config.json:/opt/config.json zyclonite/nassh-relay`

config.json:
<pre>
{
  "webservice":{
    "hostname":"0.0.0.0",
    "port":443
  },
  "application":{
    "authentication":true,
    "max-sessions":100,
    "tcp-session-timeout":1200,
    "auth-session-timeout":600
  },
  "accesslist":[{
    "id":"xxx",
    "access":[
      {"network":"0.0.0.0/0"}
    ]
  }],
  "whitelist":[
    {"host":"1.1.1.1"}
  ],
  "blacklist":[
    {"network":"192.168.0.0/16"},
    {"network":"169.254.0.0/16"},
    {"network":"172.16.0.0/12"},
    {"network":"127.0.0.0/8"},
    {"network":"10.0.0.0/8"},
    {"network":"0.0.0.0/8"},
    {"network":"fe80::/10"},
    {"host":"127.0.0.1"}
  ],
  "google-sso":{
    "title":"nassh-relay g+ Single Sign On",
    "client-id":"xxx",
    "client-secret":"xxx"
  }
}
</pre>

sites-enabled/default:
<pre>
##
# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# http://wiki.nginx.org/Pitfalls
# http://wiki.nginx.org/QuickStart
# http://wiki.nginx.org/Configuration
#
# Generally, you will want to move this file somewhere, and start with a clean
# file but keep this around for reference. Or just disable in sites-enabled.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##

# Virtual Host configuration for example.com
#
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.
#
server {
    listen  80;
    listen  443 ssl;

    ssl_certificate         /etc/letsencrypt/live/fqdn/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/fqdn/privkey.pem;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    server_name fqdn;

    root /var/www/fqdn;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
    location /cookie {
            proxy_pass http://localhost:8022/cookie;
            proxy_set_header Host $host;
            proxy_set_header Accept-Encoding "";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_max_temp_file_size 0;
    }

    location /proxy {
            proxy_pass http://localhost:8022/proxy;
            proxy_set_header Host $host;
            proxy_set_header Accept-Encoding "";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_max_temp_file_size 0;
    }

    location /read {
            proxy_pass http://localhost:8022/read;
            proxy_set_header Host $host;
            proxy_set_header Accept-Encoding "";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_max_temp_file_size 0;
    }

    location /write {
            proxy_pass http://localhost:8022/write;
            proxy_set_header Host $host;
            proxy_set_header Accept-Encoding "";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_max_temp_file_size 0;
    }

    location /connect {
            proxy_pass http://localhost:8022/connect;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 10m;
            proxy_set_header Host $host;
            proxy_set_header Accept-Encoding "";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_max_temp_file_size 0;
    }
}
</pre>

**Comment by zyclonite** [comment]
thank you for the configuration, i could reproduce the problem now
i will update the documentation on that topic

in short:
change your config to set the host header below
`proxy_set_header Host $server_name:$server_port;`

there is as well another thing you may have not run into yet
disable proxy buffering with
`proxy_buffering off;`

**Comment by qorron** [comment]
thanks, that worked!
