### ISSUE TITLE
Getting 404 when using nginx, works fine without it. 

### ISSUE THREAD

**Issue by PaulMH** [zyclonite/nassh-relay#4]
I copied the config example file you have, only change was the port number. Getting 404 on the connect request, cookie returns 302, proxy returns 200. Not sure what I'm doing wrong. 
Debug nginx log
2017/05/25 08:16:43 [debug] 32488#32488: accept on 0.0.0.0:7654, ready: 0
2017/05/25 08:16:43 [debug] 32488#32488: posix_memalign: 000055FB97AB3CD0:512 @16
2017/05/25 08:16:43 [debug] 32488#32488: *15 accept: 172.3.140.188:45192 fd:12
2017/05/25 08:16:43 [debug] 32488#32488: *15 event timer add: 12: 60000:1495700263489
2017/05/25 08:16:43 [debug] 32488#32488: *15 reusable connection: 1
2017/05/25 08:16:43 [debug] 32488#32488: *15 epoll add event: fd:12 op:1 ev:80002001
2017/05/25 08:16:43 [debug] 32488#32488: *15 http wait request handler
2017/05/25 08:16:43 [debug] 32488#32488: *15 malloc: 000055FB97AB0F20:1024
2017/05/25 08:16:43 [debug] 32488#32488: *15 recv: fd:12 590 of 1024
2017/05/25 08:16:43 [debug] 32488#32488: *15 reusable connection: 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 posix_memalign: 000055FB97AA3F70:4096 @16
2017/05/25 08:16:43 [debug] 32488#32488: *15 http process request line
2017/05/25 08:16:43 [debug] 32488#32488: *15 http request line: "GET /connect?sid=13311622-c8c7-48f2-958f-114f87f1558d&ack=0&pos=0 HTTP/1.1"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http uri: "/connect"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http args: "sid=13311622-c8c7-48f2-958f-114f87f1558d&ack=0&pos=0"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http exten: ""
2017/05/25 08:16:43 [debug] 32488#32488: *15 http process request header line
2017/05/25 08:16:43 [debug] 32488#32488: *15 http header: "Host: 52.201.235.17:7654"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http header: "Connection: Upgrade"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http header: "Pragma: no-cache"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http header: "Cache-Control: no-cache"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http header: "Upgrade: websocket"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http header: "Origin: chrome-extension://pnhechapfaindjhompbnflcldabbghjo"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http header: "Sec-WebSocket-Version: 13"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http header: "User-Agent: Mozilla/5.0 (X11; CrOS x86_64 9334.72.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.140 Safari/537.36"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http header: "Accept-Encoding: gzip, deflate, sdch"
2017/05/25 08:16:43 [debug] 32488#32488: *15 posix_memalign: 000055FB97A96BD0:4096 @16
2017/05/25 08:16:43 [debug] 32488#32488: *15 http header: "Accept-Language: en-US,en;q=0.8"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http header: "Sec-WebSocket-Key: /Ky6pmyqQECtC6Y1NgonZw=="
2017/05/25 08:16:43 [debug] 32488#32488: *15 http header: "Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http header done
2017/05/25 08:16:43 [debug] 32488#32488: *15 event timer del: 12: 1495700263489
2017/05/25 08:16:43 [debug] 32488#32488: *15 generic phase: 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 rewrite phase: 1
2017/05/25 08:16:43 [debug] 32488#32488: *15 test location: "/proxy"
2017/05/25 08:16:43 [debug] 32488#32488: *15 test location: "/cookie"
2017/05/25 08:16:43 [debug] 32488#32488: *15 test location: "/connect"
2017/05/25 08:16:43 [debug] 32488#32488: *15 using configuration "/connect"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http cl:-1 max:1048576
2017/05/25 08:16:43 [debug] 32488#32488: *15 rewrite phase: 3
2017/05/25 08:16:43 [debug] 32488#32488: *15 post rewrite phase: 4
2017/05/25 08:16:43 [debug] 32488#32488: *15 generic phase: 5
2017/05/25 08:16:43 [debug] 32488#32488: *15 generic phase: 6
2017/05/25 08:16:43 [debug] 32488#32488: *15 generic phase: 7
2017/05/25 08:16:43 [debug] 32488#32488: *15 access phase: 8
2017/05/25 08:16:43 [debug] 32488#32488: *15 access phase: 9
2017/05/25 08:16:43 [debug] 32488#32488: *15 access phase: 10
2017/05/25 08:16:43 [debug] 32488#32488: *15 post access phase: 11
2017/05/25 08:16:43 [debug] 32488#32488: *15 http init upstream, client timer: 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 epoll add event: fd:12 op:3 ev:80002005
2017/05/25 08:16:43 [debug] 32488#32488: *15 http script copy: "Host: "
2017/05/25 08:16:43 [debug] 32488#32488: *15 http script var: "52.201.235.17:7654"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http script copy: "
"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http script copy: "X-Real-IP: "
2017/05/25 08:16:43 [debug] 32488#32488: *15 http script var: "172.3.140.188"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http script copy: "
"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http script copy: "Connection: close
"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http script copy: ""
2017/05/25 08:16:43 [debug] 32488#32488: *15 http script copy: ""
2017/05/25 08:16:43 [debug] 32488#32488: *15 http script copy: ""
2017/05/25 08:16:43 [debug] 32488#32488: *15 http script copy: ""
2017/05/25 08:16:43 [debug] 32488#32488: *15 http proxy header: "Pragma: no-cache"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http proxy header: "Cache-Control: no-cache"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http proxy header: "Origin: chrome-extension://pnhechapfaindjhompbnflcldabbghjo"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http proxy header: "Sec-WebSocket-Version: 13"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http proxy header: "User-Agent: Mozilla/5.0 (X11; CrOS x86_64 9334.72.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.140 Safari/537.36"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http proxy header: "Accept-Encoding: gzip, deflate, sdch"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http proxy header: "Accept-Language: en-US,en;q=0.8"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http proxy header: "Sec-WebSocket-Key: /Ky6pmyqQECtC6Y1NgonZw=="
2017/05/25 08:16:43 [debug] 32488#32488: *15 http proxy header: "Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http proxy header:
"GET /connect?sid=13311622-c8c7-48f2-958f-114f87f1558d&ack=0&pos=0 HTTP/1.0
Host: 52.201.235.17:7654
X-Real-IP: 172.3.140.188
Connection: close
Pragma: no-cache
Cache-Control: no-cache
Origin: chrome-extension://pnhechapfaindjhompbnflcldabbghjo
Sec-WebSocket-Version: 13
User-Agent: Mozilla/5.0 (X11; CrOS x86_64 9334.72.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.140 Safari/537.36
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Sec-WebSocket-Key: /Ky6pmyqQECtC6Y1NgonZw==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits

"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http cleanup add: 000055FB97A975A8
2017/05/25 08:16:43 [debug] 32488#32488: *15 get rr peer, try: 1
2017/05/25 08:16:43 [debug] 32488#32488: *15 stream socket 13
2017/05/25 08:16:43 [debug] 32488#32488: *15 epoll add connection: fd:13 ev:80002005
2017/05/25 08:16:43 [debug] 32488#32488: *15 connect to 127.0.0.1:8022, fd:13 #16
2017/05/25 08:16:43 [debug] 32488#32488: *15 http upstream connect: -2
2017/05/25 08:16:43 [debug] 32488#32488: *15 posix_memalign: 000055FB97A92980:128 @16
2017/05/25 08:16:43 [debug] 32488#32488: *15 event timer add: 13: 60000:1495700263489
2017/05/25 08:16:43 [debug] 32488#32488: *15 http finalize request: -4, "/connect?sid=13311622-c8c7-48f2-958f-114f87f1558d&ack=0&pos=0" a:1, c:2
2017/05/25 08:16:43 [debug] 32488#32488: *15 http request count:2 blk:0
2017/05/25 08:16:43 [debug] 32488#32488: *15 http run request: "/connect?sid=13311622-c8c7-48f2-958f-114f87f1558d&ack=0&pos=0"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http upstream check client, write event:1, "/connect"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http upstream recv(): -1 (11: Resource temporarily unavailable)
2017/05/25 08:16:43 [debug] 32488#32488: *15 http upstream request: "/connect?sid=13311622-c8c7-48f2-958f-114f87f1558d&ack=0&pos=0"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http upstream send request handler
2017/05/25 08:16:43 [debug] 32488#32488: *15 http upstream send request
2017/05/25 08:16:43 [debug] 32488#32488: *15 http upstream send request body
2017/05/25 08:16:43 [debug] 32488#32488: *15 chain writer buf fl:1 s:594
2017/05/25 08:16:43 [debug] 32488#32488: *15 chain writer in: 000055FB97A975E0
2017/05/25 08:16:43 [debug] 32488#32488: *15 writev: 594 of 594
2017/05/25 08:16:43 [debug] 32488#32488: *15 chain writer out: 0000000000000000
2017/05/25 08:16:43 [debug] 32488#32488: *15 event timer del: 13: 1495700263489
2017/05/25 08:16:43 [debug] 32488#32488: *15 event timer add: 13: 60000:1495700263489
2017/05/25 08:16:43 [debug] 32488#32488: *15 http upstream request: "/connect?sid=13311622-c8c7-48f2-958f-114f87f1558d&ack=0&pos=0"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http upstream process header
2017/05/25 08:16:43 [debug] 32488#32488: *15 malloc: 000055FB97A97BE0:4096
2017/05/25 08:16:43 [debug] 32488#32488: *15 recv: fd:13 139 of 4096
2017/05/25 08:16:43 [debug] 32488#32488: *15 http proxy status 404 "404 Not Found"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http proxy header: "content-type: text/html; charset=utf-8"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http proxy header: "Content-Length: 53"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http proxy header done
2017/05/25 08:16:43 [debug] 32488#32488: *15 xslt filter header
2017/05/25 08:16:43 [debug] 32488#32488: *15 HTTP/1.1 404 Not Found
Server: nginx/1.10.0 (Ubuntu)
Date: Thu, 25 May 2017 08:16:43 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Content-Encoding: gzip

2017/05/25 08:16:43 [debug] 32488#32488: *15 write new buf t:1 f:0 000055FB97A97948, pos 000055FB97A97948, size: 210 file: 0, size: 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 http write filter: l:0 f:0 s:210
2017/05/25 08:16:43 [debug] 32488#32488: *15 http proxy filter init s:404 h:0 c:0 l:53
2017/05/25 08:16:43 [debug] 32488#32488: *15 tcp_nodelay
2017/05/25 08:16:43 [debug] 32488#32488: *15 http upstream process non buffered downstream
2017/05/25 08:16:43 [debug] 32488#32488: *15 http output filter "/connect?sid=13311622-c8c7-48f2-958f-114f87f1558d&ack=0&pos=0"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http copy filter: "/connect?sid=13311622-c8c7-48f2-958f-114f87f1558d&ack=0&pos=0"
2017/05/25 08:16:43 [debug] 32488#32488: *15 image filter
2017/05/25 08:16:43 [debug] 32488#32488: *15 xslt filter body
2017/05/25 08:16:43 [debug] 32488#32488: *15 http postpone filter "/connect?sid=13311622-c8c7-48f2-958f-114f87f1558d&ack=0&pos=0" 000055FB97A97A20
2017/05/25 08:16:43 [debug] 32488#32488: *15 http gzip filter
2017/05/25 08:16:43 [debug] 32488#32488: *15 malloc: 000055FB97AEEA60:12288
2017/05/25 08:16:43 [debug] 32488#32488: *15 gzip alloc: n:1 s:5936 a:8192 p:000055FB97AEEA60
2017/05/25 08:16:43 [debug] 32488#32488: *15 gzip alloc: n:512 s:2 a:1024 p:000055FB97AF0A60
2017/05/25 08:16:43 [debug] 32488#32488: *15 gzip alloc: n:512 s:2 a:1024 p:000055FB97AF0E60
2017/05/25 08:16:43 [debug] 32488#32488: *15 gzip alloc: n:512 s:2 a:1024 p:000055FB97AF1260
2017/05/25 08:16:43 [debug] 32488#32488: *15 gzip alloc: n:256 s:4 a:1024 p:000055FB97AF1660
2017/05/25 08:16:43 [debug] 32488#32488: *15 gzip in: 000055FB97A97B08
2017/05/25 08:16:43 [debug] 32488#32488: *15 gzip in_buf:000055FB97A97A30 ni:000055FB97A97C36 ai:53
2017/05/25 08:16:43 [debug] 32488#32488: *15 malloc: 000055FB97A98BF0:4096
2017/05/25 08:16:43 [debug] 32488#32488: *15 deflate in: ni:000055FB97A97C36 no:000055FB97A98BF0 ai:53 ao:4096 fl:2 redo:0
2017/05/25 08:16:43 [debug] 32488#32488: *15 deflate out: ni:000055FB97A97C6B no:000055FB97A98C23 ai:0 ao:4045 rc:0
2017/05/25 08:16:43 [debug] 32488#32488: *15 gzip in_buf:000055FB97A97A30 pos:000055FB97A97C36
2017/05/25 08:16:43 [debug] 32488#32488: *15 posix_memalign: 000055FB97A99C00:4096 @16
2017/05/25 08:16:43 [debug] 32488#32488: *15 http chunk: 10
2017/05/25 08:16:43 [debug] 32488#32488: *15 http chunk: 51
2017/05/25 08:16:43 [debug] 32488#32488: *15 write old buf t:1 f:0 000055FB97A97948, pos 000055FB97A97948, size: 210 file: 0, size: 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 write new buf t:1 f:0 000055FB97A99CC0, pos 000055FB97A99CC0, size: 4 file: 0, size: 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 write new buf t:0 f:0 0000000000000000, pos 000055FB977519E0, size: 10 file: 0, size: 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 write new buf t:1 f:0 000055FB97A98BF0, pos 000055FB97A98BF0, size: 51 file: 0, size: 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 write new buf t:0 f:0 0000000000000000, pos 000055FB97520F26, size: 2 file: 0, size: 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 http write filter: l:0 f:1 s:277
2017/05/25 08:16:43 [debug] 32488#32488: *15 http write filter limit 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 writev: 277 of 277
2017/05/25 08:16:43 [debug] 32488#32488: *15 http write filter 0000000000000000
2017/05/25 08:16:43 [debug] 32488#32488: *15 gzip in: 0000000000000000
2017/05/25 08:16:43 [debug] 32488#32488: *15 http copy filter: 0 "/connect?sid=13311622-c8c7-48f2-958f-114f87f1558d&ack=0&pos=0"
2017/05/25 08:16:43 [debug] 32488#32488: *15 finalize http upstream request: 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 finalize http proxy request
2017/05/25 08:16:43 [debug] 32488#32488: *15 free rr peer 1 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 close http upstream connection: 13
2017/05/25 08:16:43 [debug] 32488#32488: *15 free: 000055FB97A92980, unused: 48
2017/05/25 08:16:43 [debug] 32488#32488: *15 event timer del: 13: 1495700263489
2017/05/25 08:16:43 [debug] 32488#32488: *15 reusable connection: 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 http output filter "/connect?sid=13311622-c8c7-48f2-958f-114f87f1558d&ack=0&pos=0"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http copy filter: "/connect?sid=13311622-c8c7-48f2-958f-114f87f1558d&ack=0&pos=0"
2017/05/25 08:16:43 [debug] 32488#32488: *15 image filter
2017/05/25 08:16:43 [debug] 32488#32488: *15 xslt filter body
2017/05/25 08:16:43 [debug] 32488#32488: *15 http postpone filter "/connect?sid=13311622-c8c7-48f2-958f-114f87f1558d&ack=0&pos=0" 00007FFCB6E79FE0
2017/05/25 08:16:43 [debug] 32488#32488: *15 http gzip filter
2017/05/25 08:16:43 [debug] 32488#32488: *15 gzip in: 000055FB97A97B88
2017/05/25 08:16:43 [debug] 32488#32488: *15 gzip in_buf:000055FB97A99D78 ni:0000000000000000 ai:0
2017/05/25 08:16:43 [debug] 32488#32488: *15 deflate in: ni:0000000000000000 no:000055FB97A98BF0 ai:0 ao:4096 fl:4 redo:0
2017/05/25 08:16:43 [debug] 32488#32488: *15 deflate out: ni:0000000000000000 no:000055FB97A98BF2 ai:0 ao:4094 rc:1
2017/05/25 08:16:43 [debug] 32488#32488: *15 gzip in_buf:000055FB97A99D78 pos:0000000000000000
2017/05/25 08:16:43 [debug] 32488#32488: *15 free: 000055FB97AEEA60
2017/05/25 08:16:43 [debug] 32488#32488: *15 http chunk: 10
2017/05/25 08:16:43 [debug] 32488#32488: *15 write new buf t:1 f:0 000055FB97A99DC8, pos 000055FB97A99DC8, size: 3 file: 0, size: 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 write new buf t:1 f:0 000055FB97A98BF0, pos 000055FB97A98BF0, size: 10 file: 0, size: 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 write new buf t:0 f:0 000055FB97A99CC0, pos 000055FB97520F21, size: 7 file: 0, size: 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 http write filter: l:1 f:1 s:20
2017/05/25 08:16:43 [debug] 32488#32488: *15 http write filter limit 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 writev: 20 of 20
2017/05/25 08:16:43 [debug] 32488#32488: *15 http write filter 0000000000000000
2017/05/25 08:16:43 [debug] 32488#32488: *15 http copy filter: 0 "/connect?sid=13311622-c8c7-48f2-958f-114f87f1558d&ack=0&pos=0"
2017/05/25 08:16:43 [debug] 32488#32488: *15 http finalize request: 0, "/connect?sid=13311622-c8c7-48f2-958f-114f87f1558d&ack=0&pos=0" a:1, c:1
2017/05/25 08:16:43 [debug] 32488#32488: *15 set http keepalive handler
2017/05/25 08:16:43 [debug] 32488#32488: *15 http close request
2017/05/25 08:16:43 [debug] 32488#32488: *15 http log handler
2017/05/25 08:16:43 [debug] 32488#32488: *15 free: 000055FB97A98BF0
2017/05/25 08:16:43 [debug] 32488#32488: *15 free: 0000000000000000
2017/05/25 08:16:43 [debug] 32488#32488: *15 free: 000055FB97A97BE0
2017/05/25 08:16:43 [debug] 32488#32488: *15 free: 000055FB97AA3F70, unused: 3
2017/05/25 08:16:43 [debug] 32488#32488: *15 free: 000055FB97A96BD0, unused: 8
2017/05/25 08:16:43 [debug] 32488#32488: *15 free: 000055FB97A99C00, unused: 3335
2017/05/25 08:16:43 [debug] 32488#32488: *15 free: 000055FB97AB0F20
2017/05/25 08:16:43 [debug] 32488#32488: *15 hc free: 0000000000000000 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 hc busy: 0000000000000000 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 reusable connection: 1
2017/05/25 08:16:43 [debug] 32488#32488: *15 event timer add: 12: 65000:1495700268491
2017/05/25 08:16:43 [debug] 32488#32488: *15 post event 000055FB97ACAC20
2017/05/25 08:16:43 [debug] 32488#32488: *15 delete posted event 000055FB97ACAC20
2017/05/25 08:16:43 [debug] 32488#32488: *15 http keepalive handler
2017/05/25 08:16:43 [debug] 32488#32488: *15 malloc: 000055FB97AB0F20:1024
2017/05/25 08:16:43 [debug] 32488#32488: *15 recv: fd:12 -1 of 1024
2017/05/25 08:16:43 [debug] 32488#32488: *15 recv() not ready (11: Resource temporarily unavailable)
2017/05/25 08:16:43 [debug] 32488#32488: *15 free: 000055FB97AB0F20
2017/05/25 08:16:43 [debug] 32488#32488: *15 http keepalive handler
2017/05/25 08:16:43 [debug] 32488#32488: *15 malloc: 000055FB97AB0F20:1024
2017/05/25 08:16:43 [debug] 32488#32488: *15 recv: fd:12 -1 of 1024
2017/05/25 08:16:43 [info] 32488#32488: *15 client 172.3.140.188 closed keepalive connection (104: Connection reset by peer)
2017/05/25 08:16:43 [debug] 32488#32488: *15 close http connection: 12
2017/05/25 08:16:43 [debug] 32488#32488: *15 event timer del: 12: 1495700268491
2017/05/25 08:16:43 [debug] 32488#32488: *15 reusable connection: 0
2017/05/25 08:16:43 [debug] 32488#32488: *15 free: 000055FB97AB0F20

Output from nassh-relay
08:16:37.498 [vert.x-eventloop-thread-0]      DEBUG n.z.n.h.CookieHandler - got request
08:16:38.646 [vert.x-eventloop-thread-0]      DEBUG n.z.n.h.ProxyHandler - got request
08:16:38.650 [vert.x-eventloop-thread-0]      INFO  n.z.n.h.ProxyHandler - Connected to ssh server: 10.10.7.128:22 (redacted-ip)

**Comment by zyclonite** [comment]
please provide your nginx config, you used in this setup

**Comment by zyclonite** [comment]
closed due to inactivity
