### ISSUE TITLE
Quick way to support SSL? 

### ISSUE THREAD

**Issue by XericZephyr** [zyclonite/nassh-relay#5]
Is is possible to quickly support SSL on the server?

Thanks.

**Comment by eldridgea** [comment]
@XericZephyr, the way I get SSL is with an nginx reverse proxy. I only allow access to the nassh port (8022) from localhost and then I install nginx and this is my config in /etc/nginx/sites-enabled/nassh

server {
	listen 443 ssl;

	server_name ssh.naphos.com default;
        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

	location /cookie {
	    proxy_pass http://localhost:8022/cookie;
            include proxy_params;
        }

    	location /proxy {
            proxy_pass http://localhost:8022/proxy;
            include proxy_params;
        }

    	location /read {
            proxy_pass http://localhost:8022/read;
            include proxy_params;
    	}

    	location /write {
            proxy_pass http://localhost:8022/write;
            include proxy_params;
    	}

    	location /connect {
            proxy_pass http://localhost:8022/connect;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 10m;
            include proxy_params;
    	}
}

**Comment by XericZephyr** [comment]
Thanks a lot. I tried it and it works now.

Hopefully SSL will be supported natively in the future.
