### ISSUE TITLE
Please show how to run nassh-relay without docker

### ISSUE THREAD

**Issue by bangert** [zyclonite/nassh-relay#9]
Thanks for nassh-relay!

The current Manual does not show how to run the nassh-relay without docker. Also i cant seem to find the Dockerfile (which presumably contains this information).

**Comment by zyclonite** [comment]
i will update the docs

in short: we use the maven docker plugin to create the container so you need to look at https://github.com/zyclonite/nassh-relay/blob/457f367dc25610bfc3b3b1c392a8befbadae3872/pom.xml#L143
or you can look into the run.sh or nassh-relay.service file (which is systemd unit format to run it as service)

**Comment by bangert** [comment]
Excellent. Thanks for the quick response!

Again: Thank you very much for the GPL release of nassh-relay.
